# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3760cb1fe407d3a3a683aad74a680ac3"
name = "my-new-awesome-app"
handle = "my-new-awesome-app-132"
application_url = "https://brochure-running-further-chad.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ohsolutions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://brochure-running-further-chad.trycloudflare.com/auth/callback",
  "https://brochure-running-further-chad.trycloudflare.com/auth/shopify/callback",
  "https://brochure-running-further-chad.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
